// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  exports.compile = function(src, options) {
    var escape_char, quote;
    if (options == null) {
      options = {};
    }
    escape_char = function(ch) {
      var hex;
      hex = ch.charCodeAt(0).toString(16);
      if (hex.length > 4) {
        hex = 'fffd';
      }
      while (hex.length < 4) {
        hex = "0" + hex;
      }
      return "\\u" + hex;
    };
    quote = function(s) {
      var ch;
      return "\"" + (((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = src.length; _i < _len; _i++) {
          ch = src[_i];
          _results.push(escape_char(ch));
        }
        return _results;
      })()).join('')) + "\"";
    };
    return "return document.createTextNode(" + (quote(src)) + ");";
  };

}).call(this);
