// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var fs, play, src;

  fs = require('fs');

  src = fs.readFileSync("" + __dirname + "/game.txt", 'utf8');

  play = require('.').play;

  play(src);

}).call(this);
