// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var $, render;

  $ = require('jquery');

  render = require('./compiler').render;

  $(function() {
    var content, textarea;
    content = $('#content');
    textarea = $('#textarea');
    return textarea.on('input', function(e) {
      var rendered, src;
      src = textarea.val();
      rendered = render(src);
      content.empty();
      content.append(rendered);
    });
  });

}).call(this);
